name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "19 9 * * 1"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swiftlang/swift:nightly-5.9-focal
    container: ${{ matrix.image }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
      - name: Run Tests
        run: swift test --enable-test-discovery
